---
- name: Demo rules with kafka as source
  hosts: localhost
  sources:
    - name: Kafka
      ansible.eda.kafka:
        topic: eda
        host: 192.168.178.68
        port: 9092
        group_id: testing
  rules:
    - name: Controller Rule
      condition: event.body.event == 1
      action:
        run_job_template:
          name: Kafka event 1
          organization: Default
    - name: Check defined
      condition: event.body.debug is defined
      action:
        debug:
    - name: Privent event
      condition: event.body.print.confirm == true
      action:
        print_event:
    - name: Stop
      condition: event.body == stop
      action:
        shutdown:
          message: Shutting because of kafka stop event
