---
- name: Demo rules with kafka as source
  hosts: localhost
  sources:
    - name: Kafka
      ansible.eda.kafka:
        topic: eda
        host: localhost
        port: 9092
        group_id: testing
  rules:
    - name: Check defined
      condition: event.body.i is defined
      action:
        debug:
    - name: Stop
      condition: event.body == stop
      action:
        shutdown:
