---
- name: Demo rules with kafka as source
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: match webhook event
      condition: event.payload.ping == "pong"
      action:
        debug:
          msg: "Rule fired successfully"

    - name: shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown: